dist: trusty
sudo: required

services:
  - docker

addons:
  code_climate:
    repo_token: 7c36f361698781d36b23e8157a68609ca06d4c231658791c6c1d9f4a7e9541dd

install:
  - docker-compose -f docker-compose.test.yml build

before_script:
  - docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml run web bin/rake db:create RAILS_ENV=test
  - docker-compose -f docker-compose.test.yml run web bin/rake db:schema:load RAILS_ENV=test
  - docker-compose down
script:
  - docker-compose -f docker-compose.test.yml run web bin/rake test

