version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
     - redis:/var/lib/redis/data
  db:
    image: postgres:alpine
    ports:
        - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .rails.env
volumes:
  redis:
  postgres:

