 # PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: one_hundred_motels_development
  pool: 5
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: one_hundred_motels_test
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: one_hundred_motels_production
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: one_hundred_motels_production
  pool: 5
  username: postgres
  password:

cucumber:
  <<: *test