require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventUsersController do

  # This should return the minimal set of attributes required to create a valid
  # EventUser. As you add validations to EventUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all event_users as @event_users" do
      event_user = EventUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:event_users).should eq([event_user])
    end
  end

  describe "GET show" do
    it "assigns the requested event_user as @event_user" do
      event_user = EventUser.create! valid_attributes
      get :show, {:id => event_user.to_param}, valid_session
      assigns(:event_user).should eq(event_user)
    end
  end

  describe "GET new" do
    it "assigns a new event_user as @event_user" do
      get :new, {}, valid_session
      assigns(:event_user).should be_a_new(EventUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_user as @event_user" do
      event_user = EventUser.create! valid_attributes
      get :edit, {:id => event_user.to_param}, valid_session
      assigns(:event_user).should eq(event_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventUser" do
        expect {
          post :create, {:event_user => valid_attributes}, valid_session
        }.to change(EventUser, :count).by(1)
      end

      it "assigns a newly created event_user as @event_user" do
        post :create, {:event_user => valid_attributes}, valid_session
        assigns(:event_user).should be_a(EventUser)
        assigns(:event_user).should be_persisted
      end

      it "redirects to the created event_user" do
        post :create, {:event_user => valid_attributes}, valid_session
        response.should redirect_to(EventUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_user as @event_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventUser.any_instance.stub(:save).and_return(false)
        post :create, {:event_user => {  }}, valid_session
        assigns(:event_user).should be_a_new(EventUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventUser.any_instance.stub(:save).and_return(false)
        post :create, {:event_user => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_user" do
        event_user = EventUser.create! valid_attributes
        # Assuming there are no other event_users in the database, this
        # specifies that the EventUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventUser.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => event_user.to_param, :event_user => { "these" => "params" }}, valid_session
      end

      it "assigns the requested event_user as @event_user" do
        event_user = EventUser.create! valid_attributes
        put :update, {:id => event_user.to_param, :event_user => valid_attributes}, valid_session
        assigns(:event_user).should eq(event_user)
      end

      it "redirects to the event_user" do
        event_user = EventUser.create! valid_attributes
        put :update, {:id => event_user.to_param, :event_user => valid_attributes}, valid_session
        response.should redirect_to(event_user)
      end
    end

    describe "with invalid params" do
      it "assigns the event_user as @event_user" do
        event_user = EventUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_user.to_param, :event_user => {  }}, valid_session
        assigns(:event_user).should eq(event_user)
      end

      it "re-renders the 'edit' template" do
        event_user = EventUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_user.to_param, :event_user => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_user" do
      event_user = EventUser.create! valid_attributes
      expect {
        delete :destroy, {:id => event_user.to_param}, valid_session
      }.to change(EventUser, :count).by(-1)
    end

    it "redirects to the event_users list" do
      event_user = EventUser.create! valid_attributes
      delete :destroy, {:id => event_user.to_param}, valid_session
      response.should redirect_to(event_users_url)
    end
  end

end
